version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: dbal
      MYSQL_DATABASE: dbal
      MYSQL_PASSWORD: passwd
    command: mysqld --sql-mode=
